core/urls.py
from django.urls import path
from . import views 
app_name='core'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('about/',views.about,name='about'),
]

mini/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path

from . import views


app_name = 'task'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.detail, name='detail'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

task/models.py
import uuid

from django.db import models

from account.models import User
from project.models import Project
from todolist.models import Todolist


class Task(models.Model):    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    todolist = models.ForeignKey(Todolist, related_name='tasks', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

task/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from project.models import Project
from todolist.models import Todolist
from .models import Task


@login_required
def add(request, project_id, todolist_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        Task.objects.create(project=project, todolist=todolist, name=name, description=description, created_by=request.user)

        return redirect(f'/projects/{project_id}/{todolist_id}/')

    return render(request, 'task/add.html')


@login_required
def detail(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)

    if request.GET.get('is_done', '') == 'yes':
        task.is_done = True
        task.save()

    return render(request, 'task/detail.html', {
        'task': task
    })


@login_required
def edit(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            task.name = name

        task.description = description
        task.save()

        return redirect(f'/projects/{project_id}/{todolist_id}/{pk}/')

    return render(request, 'task/edit.html', {
        'task': task
    })


@login_required
def delete(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)
    task.delete()

    return redirect(f'/projects/{project_id}/{todolist_id}/')

task/templates/task/add.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add task</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white"></textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>
{% endblock %}

task/templates/task/detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ task.name }}</h1>

    <p><strong class="font-bold">Status:</strong> {% if task.is_done %}done{% else %}not done{% endif %}</p>

    {% if task.description %}
        <p class="mb-6">{{ task.description }}</p>
    {% endif %}

    {% if not task.is_done %}
        <a href="?is_done=yes" class="py-4 px-8 bg-emerald-600 text-white inline-block">Mark as done</a>
    {% endif %}
    <a href="{% url 'task:edit' task.project_id task.todolist_id task.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="{% url 'task:delete' task.project_id task.todolist_id task.id %}" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>
{% endblock %}

task/templates/task/edit.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit task</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input value="{{ task.name }}" name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white">{{ task.description }}</textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Save changes</button>
        </div>
    </form>
{% endblock %}