core/urls.py
from django.urls import path
from . import views 
app_name='core'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('about/',views.about,name='about'),
]

mini/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

task/urls.py
from django.urls import path

from . import views


app_name = 'task'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.detail, name='detail'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

todolist/urls.py
from django.urls import path

from . import views


app_name = 'todolist'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

todolist/models.py
import uuid

from django.db import models

from account.models import User
from project.models import Project


class Todolist(models.Model):    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='todolists', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='todolists', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

todolist/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .models import Todolist
from project.models import Project


@login_required
def todolist(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    return render(request, 'todolist/todolist.html', {
        'project': project,
        'todolist': todolist
    })


@login_required
def add(request, project_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            Todolist.objects.create(project=project, name=name, description=description, created_by=request.user)

            return redirect(f'/projects/{project_id}/')

    return render(request, 'todolist/add.html', {
        'project': project
    })


@login_required
def edit(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            todolist.name = name
            todolist.description = description
            todolist.save()

            return redirect(f'/projects/{project_id}/{pk}/')

    return render(request, 'todolist/edit.html', {
        'project': project,
        'todolist': todolist
    })


@login_required
def delete(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = Todolist.objects.filter(project=project).get(pk=pk)
    todolist.delete()

    return redirect(f'/projects/{project_id}/')

todolist/templates/todolist/add.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add todolist</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white"></textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>
{% endblock %}

todolist/templates/todolist/edit.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit todolist</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" value="{{ todolist.name }}" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white">{{ todolist.description }}</textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>
{% endblock %}

todolist/templates/todolist/todolist.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ todolist.name }}</h1>

    {% if todolist.description %}
        <p class="mb-6">{{ todolist.description }}</p>
    {% endif %}

    <a href="{% url 'task:add' project.id todolist.id %}" class="py-4 px-8 bg-emerald-600 text-white inline-block">Add task</a>
    <a href="{% url 'todolist:edit' project.id todolist.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="{% url 'todolist:delete' project.id todolist.id %}" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for task in todolist.tasks.all %}
            <div class="py-6 px-6 bg-slate-200">
                <a href="{% url 'task:detail' todolist.project.id todolist.id task.id %}">
                    <h2 class="mb-4 text-xl">{{ task.name }}</h2>

                    <p class="text-sm text-slate-600">
                        {{ task.description }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}