core/urls.py
from django.urls import path
from . import views 
app_name='core'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('about/',views.about,name='about'),
]

mini/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('account.urls')),
    path('projects/', include('project.urls')),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path

from . import views


app_name = 'project'


urlpatterns = [
    path('', views.projects, name='projects'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
    path('<uuid:project_id>/files/upload/', views.upload_file, name='upload_file'),
    path('<uuid:project_id>/files/<uuid:pk>/delete/', views.delete_file, name='delete_file'),
    path('<uuid:project_id>/notes/add/', views.add_note, name='add_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/', views.note_detail, name='note_detail'),
    path('<uuid:project_id>/notes/<uuid:pk>/edit/', views.note_edit, name='note_edit'),
    path('<uuid:project_id>/notes/<uuid:pk>/delete/', views.note_delete, name='note_delete'),
]

todolist/urls.py
from django.urls import path

from . import views


app_name = 'todolist'


urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.todolist, name='todolist'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
]

project/models.py
import uuid

from django.db import models

from account.models import User


class Project(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ProjectFile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='files', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    attachment = models.FileField(upload_to='projectfiles')

    def __str__(self):
        return self.name
    

class ProjectNote(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    project = models.ForeignKey(Project, related_name='notes', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

project/forms.py
from django.forms import ModelForm

from .models import ProjectFile


class ProjectFileForm(ModelForm):
    class Meta:
        model = ProjectFile
        fields = ('name', 'attachment',)

project/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import ProjectFileForm
from .models import Project, ProjectNote


@login_required
def projects(request):
    projects = Project.objects.filter(created_by=request.user)

    return render(request, 'project/projects.html', {
        'projects': projects
    })


@login_required
def project(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)

    return render(request, 'project/project.html', {
        'project': project
    })


@login_required
def add(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            Project.objects.create(name=name, description=description, created_by=request.user)

            return redirect('/projects/')
        else:
            print('Not valid')

    return render(request, 'project/add.html')


@login_required
def edit(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')

        if name:
            project.name = name
            project.description = description
            project.save()

            return redirect('/projects/')
    
    return render(request, 'project/edit.html', {
        'project': project
    })


@login_required
def delete(request, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=pk)
    project.delete()

    return redirect('/projects/')


# Files


@login_required
def upload_file(request, project_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)

    if request.method == 'POST':
        form = ProjectFileForm(request.POST, request.FILES)

        if form.is_valid():
            projectfile = form.save(commit=False)
            projectfile.project = project
            projectfile.save()

            return redirect(f'/projects/{project_id}/')
    else:
        form = ProjectFileForm()

    return render(request, 'project/upload_file.html', {
        'project': project,
        'form': form
    })


@login_required
def delete_file(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    projectfile = project.files.get(pk=pk)
    projectfile.delete()

    return redirect(f'/projects/{project_id}/')


# Notes


@login_required
def add_note(request, project_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        body = request.POST.get('body', '')

        if name and body:
            ProjectNote.objects.create(
                project=project,
                name=name,
                body=body
            )

            return redirect(f'/projects/{project_id}/')

    return render(request, 'project/add_note.html', {
        'project': project
    })


@login_required
def note_detail(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    note = project.notes.get(pk=pk)

    return render(request, 'project/note_detail.html', {
        'project': project,
        'note': note
    })


@login_required
def note_edit(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    note = project.notes.get(pk=pk)

    if request.method == 'POST':
        name = request.POST.get('name', '')
        body = request.POST.get('body', '')

        if name and body:
            note.name = name
            note.body = body
            note.save()

            return redirect(f'/projects/{project_id}/')

    return render(request, 'project/note_edit.html', {
        'project': project,
        'note': note
    })


@login_required
def note_delete(request, project_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    note = project.notes.get(pk=pk)
    note.delete()

    return redirect(f'/projects/{project_id}/')

project/templates/project/add.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add project</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white"></textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>
{% endblock %}

project/templates/project/add_note.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Add note</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Body</label><br>
            <textarea name="body" class="w-full py-4 px-6 bg-slate-500 text-white" rows="20"></textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>
{% endblock %}

project/templates/project/edit.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit project</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input name="name" value="{{ project.name }}" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Description</label><br>
            <textarea name="description" class="w-full py-4 px-6 bg-slate-500 text-white">{{ project.description }}</textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>
{% endblock %}

project/templates/project/note_detail.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ note.name }}</h1>

    <a href="{% url 'project:note_edit' project.id note.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="{% url 'project:note_delete' project.id note.id %}" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>

    <p class="mb-6">{{ note.body }}</p>
{% endblock %}

project/templates/project/note_edit.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Edit note</h1>

    <form class="mt-6 space-y-4" method="post" action=".">
        {% csrf_token %}

        <div>
            <label>Name</label><br>
            <input value="{{ note.name }}" name="name" type="text" class="w-full py-4 px-6 bg-slate-500 text-white">
        </div>

        <div>
            <label>Body</label><br>
            <textarea name="body" class="w-full py-4 px-6 bg-slate-500 text-white" rows="20">{{ note.body }}</textarea>
        </div>

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Save changes</button>
        </div>
    </form>
{% endblock %}

project/templates/project/project.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{ project.name }}</h1>

    {% if project.description %}
        <p class="mb-6">{{ project.description }}</p>
    {% endif %}

    <a href="{% url 'todolist:add' project.id %}" class="py-4 px-8 bg-emerald-600 text-white inline-block">Add todolist</a>
    <a href="{% url 'project:edit' project.id %}" class="py-4 px-8 bg-sky-600 text-white inline-block">Edit</a>
    <a href="{% url 'project:delete' project.id %}" class="py-4 px-8 bg-amber-600 text-white inline-block">Delete</a>

    <h2 class="mt-6 text-2xl">Todo lists</h2>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for todolist in project.todolists.all %}
            <div class="py-6 px-6 bg-slate-200">
                <a href="{% url 'todolist:todolist' project.id todolist.id %}">
                    <h3 class="mb-4 text-xl">{{ todolist.name }}</h3>

                    <p class="text-sm text-slate-600">
                        {{ todolist.description }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>

    <h2 class="mt-6 text-2xl">Files</h2>

    <a href="{% url 'project:upload_file' project.id %}" class="mt-6 py-4 px-8 bg-slate-600 text-white inline-block">Upload file</a>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for projectfile in project.files.all %}
            <div class="py-6 px-6 bg-slate-200">
                <h3 class="mb-4 text-xl">{{ projectfile.name }}</h3>

                <a href="{{ projectfile.attachment.url }}" target="_blank" class="text-sm text-slate-600">
                    Download file
                </a>

                |

                <a href="{% url 'project:delete_file' project.id projectfile.id %}" class="text-sm text-slate-600">
                    Delete
                </a>
            </div>
        {% endfor %}
    </div>

    <h2 class="mt-6 text-2xl">Notes</h2>

    <a href="{% url 'project:add_note' project.id %}" class="mt-6 py-4 px-8 bg-slate-600 text-white inline-block">Add note</a>

    <div class="mt-6 grid grid-cols-4 gap-4">
        {% for note in project.notes.all %}
            <div class="py-6 px-6 bg-slate-200">
                <a href="{% url 'project:note_detail' project.id note.id %}">
                    <h3 class="mb-4 text-xl">{{ note.name }}</h3>

                    <p class="text-sm text-slate-600">
                        {{ note.body|truncatechars:50 }}
                    </p>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

project/templates/project/projects.html
{% extends 'core/base.html' %}
{% block content%}
<h1 class="mb-6 text-3xl">Projects</h1>

<a href="{%url 'project:add'%} " class="py-4 px-8 bg-sky-600 text-white inline-block">Add new project</a>

<div class="mt-6 grid grid-cols-4 gap-4">
  {%for project in projects %}
  <div class="py-6 px-6 bg-slate-200">
    <a href="{% url 'project:project' project.id%}">
    <h2 class="mb-4 text-xl">{{project.name}}</h2>

    <p class="text-sm text-slate-600">{{project.description}} </p>
</a>
</div>
  {%endfor%}
</div>
{% endblock%}

project/templates/project/upload_file.html
{% extends 'core/base.html' %}

{% block content %}
    <h1 class="mb-6 text-3xl">Upload file to "{{ project.name }}"</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        {{ form.as_p }}

        <div>
            <button class="py-4 px-8 bg-sky-600 text-white">Submit</button>
        </div>
    </form>
{% endblock %}